Pin autopep8's pystyle depedency
https://github.com/hhatto/autopep8/issues/689

With latest pycodestyle (2.11), we get the following error:

    AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_around_operator'. Did you mean: 'whitespace_around_operator'?

autopep8 will need an update to match this. Until then, we have to stay
back on 2.10